name: "Smoke Tests"

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  merge_group:

jobs:
  smoke-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"
        cache: 'pip'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install setuptools
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Install build dependencies
      run: |
        python -m pip install build
    - name: Build and install package
      run: |
        python -m build
        pip install dist/*.whl
    - name: Run smoke tests
      run: |
        reddacted --help
